# Generated by Django 2.0.3 on 2018-05-17 23:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scope',
            fields=[
                ('name', models.PositiveSmallIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Название зоны')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Заголовок зоны')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание зоны')),
                ('back_url', models.URLField(max_length=255, verbose_name='Домен зоны')),
                ('hours_exp', models.PositiveSmallIntegerField(default=168, verbose_name='Часов до сгорания токена')),
                ('secret', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Внешний ключ')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='scopes/icon', verbose_name='Иконка зоны')),
            ],
            options={
                'verbose_name': 'Зона',
                'verbose_name_plural': 'Зоны',
            },
        ),
        migrations.CreateModel(
            name='ScopeStyles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_to_main', models.URLField(blank=True, max_length=255, null=True, verbose_name='Стили контейнера')),
                ('url_to_login', models.URLField(blank=True, max_length=255, null=True, verbose_name='Стили формы авторизации')),
                ('url_to_registration', models.URLField(blank=True, max_length=255, null=True, verbose_name='Стили формы регистрации')),
            ],
            options={
                'verbose_name': 'Стилизация зоны',
                'verbose_name_plural': 'Стилизация зон',
            },
        ),
    ]
