# Generated by Django 2.0.3 on 2018-05-17 23:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scopes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scope',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='scope',
            name='styles',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scopes.ScopeStyles', verbose_name='Кастомные стили'),
        ),
    ]
