# Generated by Django 2.0.3 on 2018-03-24 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scopes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scope',
            options={'verbose_name': 'Зона', 'verbose_name_plural': 'Зоны'},
        ),
        migrations.AlterField(
            model_name='scope',
            name='back_url',
            field=models.URLField(max_length=255, verbose_name='Обратный адрес зоны'),
        ),
    ]
