# Generated by Django 2.0.3 on 2018-05-08 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scopes', '0004_scope_icon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scope',
            old_name='back_url',
            new_name='domain',
        ),
    ]
