# Generated by Django 2.0.3 on 2018-05-26 22:51

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('scopes', '0004_auto_20180526_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='scope',
            name='big_icon',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=75, size=[1200, 800], upload_to='scopes/icon', verbose_name='Иконка зоны'),
        ),
        migrations.AlterField(
            model_name='scope',
            name='icon',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=75, size=[600, 400], upload_to='scopes/icon', verbose_name='Иконка зоны'),
        ),
    ]
