# Generated by Django 2.0.3 on 2018-05-09 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scopes', '0005_auto_20180508_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scope',
            name='domain',
            field=models.CharField(max_length=255, verbose_name='Домен зоны'),
        ),
    ]
